### ISSUE TITLE
Automate dwc mapping ?

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/sk-analyse#18]
@DimEvil automate dwc mapping as well ? 

ifso, which do you prefer ?
1. add you as reviewer  - or -
2. `@` mention you in pull request - or -
3. other - or -
4. neither

_Originally posted by @SanderDevisscher in https://github.com/inbo/sk-analyse/pull/17#discussion_r1059331507_

**Comment by DimEvil** [comment]
2. is ok!

**Comment by SanderDevisscher** [comment]
@DimEvil klopt het dat de volgorde van de scripts de volgende is:

1. [dwc_mapping.Rmd](https://github.com/inbo/sk-analyse/blob/main/script/dwc_mapping.Rmd)
2. [dwc_mapping_bycatch.Rmd](https://github.com/inbo/sk-analyse/blob/main/script/dwc_mapping_bycatch.Rmd)
3. [dwc_joinbycatch_catch.Rmd](https://github.com/inbo/sk-analyse/blob/main/script/dwc_joinbycatch_catch.Rmd)

**Comment by DimEvil** [comment]
Ja! Dat klopt

Op vr 27 jan. 2023 13:09 schreef Sander Devisscher ***@***.***

**Comment by SanderDevisscher** [comment]
@DimEvil zou het kunnen dat je de packages `uuid` en `rgbif` niet effectief gebruikt in je dwc scripts ? Ik vraag het omdat ik `script/install_packages_dwc.R` zo licht mogelijk wil houden.
