### ISSUE TITLE
add logic to add fuik info to gbif data

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/sk-analyse#27]
We need to add data which can help us determine the number of fykes used in a single event to the new gbif dataset. In the old dataset we added this info to the locality column. Therefor I suggest the following steps: 

- [x] mutate new column named `locality = paste(Locatie, "(no_fuiken:", no_fuiken, ")")` somewhere before this select:

https://github.com/inbo/sk-analyse/blob/3a8e594734f211e89c72ef6284d892448abd3b4e/script/data_cleaning_afvangsten.Rmd#L255-L263

- [ ] change locatie into locality here:

https://github.com/inbo/sk-analyse/blob/3a8e594734f211e89c72ef6284d892448abd3b4e/script/dwc_mapping.Rmd#L256

- [ ] republish ?

@DimEvil is this sufficient to get this info into the new gbif dataset ?

**Comment by SanderDevisscher** [comment]
@DimEvil ik heb de kolom `no_fuiken` terug toegevoegd aan de afvangsten. Bij de afvangsten was de kolom reeds aanwezig. 

een vraagje, is het een probleem dat de Occurrence ID iedere keer overschreven wordt ?

**Comment by DimEvil** [comment]
@SanderDevisscher  Dat is een probleem. We hebben een uniek ID nodig dat stabiel blijft.

**Comment by SanderDevisscher** [comment]
@DimEvil ik heb ook logica voorzien om de UUIDs te stabiliseren. Ik stel voor dat we de volledige dataset overschrijven na het toevoegen van de dynamic measurement `no_fuiken`.
